# Generated by Django 5.2.7 on 2025-10-24 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='사용자 이름')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일')),
                ('is_completed', models.BooleanField(default=False, verbose_name='완료 여부')),
            ],
            options={
                'verbose_name': '설문',
                'verbose_name_plural': '설문들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=10, unique=True, verbose_name='문항 ID')),
                ('question_text', models.TextField(verbose_name='문항 내용')),
                ('question_type', models.CharField(choices=[('single', '단일 선택'), ('multiple', '다중 선택'), ('drag', '드래그 정렬'), ('slider', '슬라이더'), ('text', '텍스트 입력')], max_length=20, verbose_name='문항 타입')),
                ('options', models.JSONField(blank=True, null=True, verbose_name='선택 옵션')),
                ('step', models.IntegerField(choices=[(1, 'STEP 1: 하드 필터'), (2, 'STEP 2: 감성 프로필'), (3, 'STEP 3: 현실 제약')], verbose_name='단계')),
                ('order', models.IntegerField(verbose_name='순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '설문 문항',
                'verbose_name_plural': '설문 문항들',
                'ordering': ['step', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='답변')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey', verbose_name='설문')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.surveyquestion', verbose_name='문항')),
            ],
            options={
                'verbose_name': '설문 답변',
                'verbose_name_plural': '설문 답변들',
                'unique_together': {('survey', 'question')},
            },
        ),
    ]
