# Generated by Django 5.2.7 on 2025-10-24 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('property_type', models.CharField(choices=[('단독주택', '단독주택'), ('타운하우스', '타운하우스'), ('빌라', '빌라'), ('연립주택', '연립주택')], default='단독주택', max_length=20, verbose_name='매물 타입')),
                ('location', models.CharField(max_length=100, verbose_name='상세 주소')),
                ('district', models.CharField(max_length=50, verbose_name='구/군')),
                ('price', models.IntegerField(verbose_name='가격 (원)')),
                ('area', models.CharField(max_length=50, verbose_name='면적 정보')),
                ('land_area', models.IntegerField(blank=True, null=True, verbose_name='대지면적 (평)')),
                ('building_area', models.IntegerField(blank=True, null=True, verbose_name='건물면적 (평)')),
                ('rooms', models.IntegerField(verbose_name='방 개수')),
                ('bathrooms', models.IntegerField(verbose_name='화장실 개수')),
                ('parking', models.IntegerField(verbose_name='주차 가능 대수')),
                ('garden_area', models.IntegerField(blank=True, null=True, verbose_name='정원 면적 (평)')),
                ('description', models.TextField(verbose_name='상세 설명')),
                ('images', models.JSONField(default=list, verbose_name='이미지 URL 목록')),
                ('persona_match', models.CharField(choices=[('해안가_라이프스타일형', '해안가 라이프스타일형'), ('도심_라이프스타일형', '도심 라이프스타일형'), ('자연친화_크리에이티브형', '자연친화 크리에이티브형'), ('산업도시_자연친화형', '산업도시 자연친화형'), ('항만_라이프스타일형', '항만 라이프스타일형'), ('모던_미니멀형', '모던 미니멀형')], max_length=50, verbose_name='페르소나 매칭')),
                ('transportation_score', models.IntegerField(default=0, verbose_name='교통 점수')),
                ('education_score', models.IntegerField(default=0, verbose_name='교육 점수')),
                ('lifestyle_score', models.IntegerField(default=0, verbose_name='생활 점수')),
                ('investment_score', models.IntegerField(default=0, verbose_name='투자 점수')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('is_featured', models.BooleanField(default=False, verbose_name='추천 매물')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '매물',
                'verbose_name_plural': '매물들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='이미지 URL')),
                ('image_type', models.CharField(choices=[('main', '메인 이미지'), ('interior', '내부 이미지'), ('exterior', '외부 이미지'), ('garden', '정원 이미지'), ('surrounding', '주변 환경')], default='main', max_length=20, verbose_name='이미지 타입')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property', verbose_name='매물')),
            ],
            options={
                'verbose_name': '매물 이미지',
                'verbose_name_plural': '매물 이미지들',
                'ordering': ['property', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PropertyInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('phone', models.CharField(max_length=20, verbose_name='연락처')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('inquiry_type', models.CharField(choices=[('viewing', '방문 상담'), ('price', '가격 문의'), ('loan', '대출 문의'), ('other', '기타')], default='viewing', max_length=20, verbose_name='문의 유형')),
                ('message', models.TextField(verbose_name='문의 내용')),
                ('is_contacted', models.BooleanField(default=False, verbose_name='연락 완료')),
                ('contacted_at', models.DateTimeField(blank=True, null=True, verbose_name='연락 완료일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property', verbose_name='매물')),
            ],
            options={
                'verbose_name': '매물 문의',
                'verbose_name_plural': '매물 문의들',
                'ordering': ['-created_at'],
            },
        ),
    ]
