# Generated by Django 5.2.7 on 2025-11-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='images',
            field=models.JSONField(blank=True, default=list, verbose_name='이미지 URL 목록'),
        ),
    ]
